server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6388
    password: pasaword
    timeout: 3000
    lettuce:
      pool:
        max-wait: 100
        max-active: 50
        min-idle: 5
        max-idle: 10
